// src/js/constants/action-types.js

export const ENTER_ZIP = "ENTER_ZIP";
export const GET_LOCATION = "GET_LOCATION";
export const FETCH_DATA_SUBMITTING = "FETCH_DATA_SUBMITTING";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const FETCH_LOC_DATA_SUBMITTING = "FETCH_LOC_DATA_SUBMITTING";
export const FETCH_LOC_DATA_SUCCESS = "FETCH_LOC_DATA_SUCCESS";
export const FETCH_LOC_DATA_ERROR = "FETCH_LOC_DATA_ERROR";
